# This is a basic workflow to help you get started with Actions

name: Meal Planner columns

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
  
  #schedule:
  #  - cron: 1 0 *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Today date plus 10 days
        run: echo $(date -d "10 days")
        
      - name: Today formatted date plus 10 days
        run: echo $(date "+%a %d-%b" -d "10 days")
