name: Generate issues report

on:
  issues:
    types: [opened, edited, deleted]
  issue_comment:
    types: [created, deleted]
    
env:
  OUTPUT_FILE_NAME: Recipes.md
  COMMITTER_EMAIL: 33549821+jcallaghan@users.noreply.github.com
  COMMITTER_NAME: James Callaghan
  COMMITTER_USERNAME: jcallaghan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: brcrista/summarize-issues@dev
      with:
        title: 'Recipes'
        configPath: '.github/workflows/issues-report-config.json'
        outputPath: ${{ env.OUTPUT_FILE_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Commit if any changes were made"
      run: |
        git remote add github "https://$COMMITTER_USERNAME:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
        if [[ `git status --porcelain` ]]; then
          git add ${OUTPUT_FILE_NAME}
          git config --global user.email $COMMITTER_EMAIL
          git config --global user.name $COMMITTER_NAME
          git commit -m "Update $OUTPUT_FILE_NAME"
          git push github HEAD:${GITHUB_REF}
        fi
